# Generated by Django 5.2.11 on 2026-02-24 14:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('primary_muscle', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('SHOULDERS', 'Shoulders'), ('CORE', 'Core'), ('QUADS', 'Quads'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('CALVES', 'Calves')], max_length=15)),
                ('pattern', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('SQUAT', 'Squat pattern'), ('HINGE', 'Hinge pattern'), ('CARRY', 'Carry'), ('CORE', 'Core'), ('OTHER', 'Other')], max_length=10)),
                ('region', models.CharField(choices=[('UPPER', 'Upper'), ('LOWER', 'Lower'), ('FULL', 'Full body')], max_length=10)),
                ('is_compound', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSecondaryMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('SHOULDERS', 'Shoulders'), ('CORE', 'Core'), ('QUADS', 'Quads'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('CALVES', 'Calves')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSecondaryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise')),
                ('secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercisesecondarymuscle')),
            ],
            options={
                'unique_together': {('exercise', 'secondary')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, null=True, related_name='exercises', through='tracker.ExerciseSecondaryLink', to='tracker.exercisesecondarymuscle'),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tracker.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('KG', 'kg'), ('LB', 'lb')], default='KG', max_length=2)),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tracker.workout')),
            ],
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['pattern', 'region'], name='tracker_exe_pattern_3e5e56_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'logged_at'], name='tracker_wor_user_id_935a31_idx'),
        ),
        migrations.AddIndex(
            model_name='set',
            index=models.Index(fields=['workout', 'exercise'], name='tracker_set_workout_c87961_idx'),
        ),
    ]
