# Generated by Django 5.2.11 on 2026-02-25 16:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, related_name='exercises', through='tracker.ExerciseSecondaryLink', to='tracker.exercisesecondarymuscle'),
        ),
        migrations.CreateModel(
            name='StrengthStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('ELITE', 'Elite')], max_length=15)),
                ('bw_multiplier', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise')),
            ],
            options={
                'indexes': [models.Index(fields=['exercise', 'level', 'sex'], name='tracker_str_exercis_59e583_idx')],
                'unique_together': {('exercise', 'level', 'sex')},
            },
        ),
    ]
