# Generated by Django 5.2.11 on 2026-02-25 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_exercise_name_alter_exercise_secondary_muscles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='logged_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
