# Generated by Django 5.2.11 on 2026-02-25 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_workout_logged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='logged_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
