# Generated by Django 5.2.11 on 2026-03-24 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_workout_logged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=40, editable=False, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
