# Generated by Django 5.2.11 on 2026-03-26 19:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_set_weight_kg_alter_set_reps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='estimated_1rm_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle',
            field=models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('SHOULDERS', 'Shoulders'), ('CORE', 'Core'), ('QUADS', 'Quads'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('CALVES', 'Calves'), ('NECK', 'Neck'), ('FOREARMS', 'Forearms')], max_length=15),
        ),
        migrations.AlterField(
            model_name='exercisesecondarymuscle',
            name='muscle_group',
            field=models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('SHOULDERS', 'Shoulders'), ('CORE', 'Core'), ('QUADS', 'Quads'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('CALVES', 'Calves'), ('NECK', 'Neck'), ('FOREARMS', 'Forearms')], max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('pr_type', models.CharField(choices=[('ESTIMATED', 'Estimated'), ('ACTUAL', 'Actual')])),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'exercise'], name='tracker_pr_user_id_0f3340_idx')],
                'unique_together': {('user', 'exercise', 'pr_type')},
            },
        ),
    ]
