# Generated by Django 5.2.11 on 2026-03-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_set_estimated_1rm_kg_alter_exercise_primary_muscle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='pr_type',
            field=models.CharField(choices=[('ESTIMATED', 'Estimated'), ('REAL', 'Real')]),
        ),
    ]
