# Generated by Django 5.2.11 on 2026-03-27 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_pr_pr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='pr_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.set'),
            preserve_default=False,
        ),
    ]
