# Generated by Django 5.2.11 on 2026-03-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_pr_pr_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr',
            name='pr_set',
        ),
    ]
