# Generated by Django 5.2.11 on 2026-03-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_pr_pr_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='pr_set',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='tracker.set'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pr',
            name='pr_type',
            field=models.CharField(choices=[('ESTIMATED', 'Estimated'), ('REAL', 'Real')], max_length=9),
        ),
    ]
