# Generated by Django 5.2.11 on 2026-03-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_pr_pr_set_alter_pr_pr_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise'),
        ),
    ]
