# Generated by Django 5.2.11 on 2026-03-30 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_pr_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='pr_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='tracker.set'),
        ),
    ]
