# Generated by Django 5.2.11 on 2026-03-31 18:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_pr_exercise_alter_pr_pr_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prs', to='tracker.exercise'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='tracker.exercise'),
        ),
        migrations.AlterField(
            model_name='strengthstandard',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_standards', to='tracker.exercise'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bodyweight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(635)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
