# Generated by Django 5.2.11 on 2026-03-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_pr_exercise_alter_pr_user_alter_set_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bodyweight',
            new_name='bodyweight_kg',
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_strength_indicative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_unit',
            field=models.CharField(choices=[('KG', 'kg'), ('LB', 'lb')], default='KG', max_length=2),
        ),
    ]
