# Generated by Django 5.2.11 on 2026-03-31 23:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_rename_bodyweight_profile_bodyweight_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='is_strength_indicative',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bodyweight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(635)]),
        ),
        migrations.CreateModel(
            name='MuscleStrengthIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('SHOULDERS', 'Shoulders'), ('CORE', 'Core'), ('QUADS', 'Quads'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('CALVES', 'Calves'), ('NECK', 'Neck'), ('FOREARMS', 'Forearms')], max_length=15)),
                ('indicator_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise')),
            ],
            options={
                'unique_together': {('muscle_group', 'exercise')},
            },
        ),
    ]
