# Generated by Django 5.2.11 on 2026-04-04 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_remove_exercise_is_strength_indicative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musclestrengthindicator',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='musclestrengthindicator',
            name='exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='tracker.exercise'),
        ),
        migrations.CreateModel(
            name='ExerciseStrengthEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pr_type', models.CharField(choices=[('ESTIMATED', 'Estimated'), ('REAL', 'Real')], max_length=9)),
                ('strength_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('ELITE', 'Elite')], max_length=12)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_evaluations', to='tracker.exercise')),
                ('pr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strength_evaluation', to='tracker.pr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
