# Generated by Django 5.2.11 on 2026-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_musclestrengthindicator_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestrengthevaluation',
            name='level_progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisestrengthevaluation',
            name='next_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('ELITE', 'Elite')], default='INTERMEDIATE', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercisestrengthevaluation',
            name='source_pr_type',
            field=models.CharField(choices=[('ESTIMATED', 'Estimated'), ('ACCURATE', 'Accurate')], max_length=9),
        ),
        migrations.AlterField(
            model_name='pr',
            name='pr_type',
            field=models.CharField(choices=[('ESTIMATED', 'Estimated'), ('ACCURATE', 'Accurate')], max_length=9),
        ),
    ]
