# Generated by Django 5.2.11 on 2026-04-07 23:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_exercisestrengthevaluation_level_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pr',
            unique_together={('user', 'exercise')},
        ),
    ]
