# Generated by Django 5.2.11 on 2026-04-11 14:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_alter_pr_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pr',
            old_name='pr_set',
            new_name='source_set',
        ),
        migrations.CreateModel(
            name='ArchivedPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('pr_type', models.CharField(choices=[('ESTIMATED', 'Estimated'), ('ACCURATE', 'Accurate')], max_length=9)),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invalidation_reason', models.CharField(choices=[('EXPIRED', 'Expired'), ('BEATEN', 'Beaten')], max_length=7)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_prs', to='tracker.exercise')),
                ('source_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archived_pr', to='tracker.set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_prs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
