# Generated by Django 5.2.11 on 2026-04-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_rename_pr_set_pr_source_set_archivedpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclestrengthindicator',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise'),
        ),
    ]
