# Generated by Django 5.2.11 on 2026-04-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_alter_musclestrengthindicator_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestrengthevaluation',
            name='score',
            field=models.DecimalField(decimal_places=2, default=3.0, editable=False, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musclestrengthindicator',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muslce_strength_indicators', to='tracker.exercise'),
        ),
    ]
