# Generated by Django 5.2.11 on 2026-04-14 17:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_exercisestrengthevaluation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='plausibility_confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3),
        ),
    ]
