# Generated by Django 5.2.11 on 2026-04-14 19:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_pr_plausibility_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedpr',
            name='plausibility_confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3),
        ),
    ]
