# Generated by Django 5.2.11 on 2026-05-05 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_archivedpr_plausibility_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpr',
            name='plausibility_confidence',
        ),
        migrations.RemoveField(
            model_name='archivedpr',
            name='pr_type',
        ),
        migrations.RemoveField(
            model_name='exercisestrengthevaluation',
            name='source_pr_type',
        ),
        migrations.RemoveField(
            model_name='pr',
            name='plausibility_confidence',
        ),
        migrations.RemoveField(
            model_name='pr',
            name='pr_type',
        ),
        migrations.AddField(
            model_name='archivedpr',
            name='reps',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pr',
            name='reps',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='PR_score',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
