# Generated by Django 5.2.11 on 2026-05-09 16:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_remove_archivedpr_plausibility_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpr',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='archivedpr',
            name='source_set',
        ),
        migrations.RemoveField(
            model_name='archivedpr',
            name='user',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='estimated_1rm_kg',
            new_name='e1rm_kg',
        ),
        migrations.AlterUniqueTogether(
            name='pr',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exercisestrengthevaluation',
            name='bodyweight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=6, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='pr',
            name='beaten_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beaten_pr', to='tracker.pr'),
        ),
        migrations.AddField(
            model_name='pr',
            name='bodyweight_kg',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(500)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pr',
            name='e1rm_kg',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pr',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='invalidation_reason',
            field=models.CharField(blank=True, choices=[('EXPIRED', 'Expired'), ('BEATEN', 'Beaten')], null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INVALIDATED', 'Invalidated')], default='INVALIDATED'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pr',
            name='reps',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bodyweight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddIndex(
            model_name='pr',
            index=models.Index(fields=['achieved_at'], name='tracker_pr_achieve_49d72d_idx'),
        ),
        migrations.AddConstraint(
            model_name='pr',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'exercise'), name='unique_active_pr_per_user_exercise'),
        ),
        migrations.DeleteModel(
            name='ArchivedPR',
        ),
    ]
