# Generated by Django 5.2.11 on 2026-05-09 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_remove_archivedpr_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisestrengthevaluation',
            name='bodyweight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
