# Generated by Django 5.2.11 on 2026-05-12 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_alter_exercisestrengthevaluation_bodyweight_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='PR_score',
        ),
        migrations.AddIndex(
            model_name='exercisestrengthevaluation',
            index=models.Index(fields=['user', 'exercise'], name='tracker_exe_user_id_e8042e_idx'),
        ),
    ]
