# Generated by Django 5.2.11 on 2026-05-16 18:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_set_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='logged_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='pr',
            name='reps',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
