# Generated by Django 5.2.11 on 2026-05-18 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_set_logged_at_alter_pr_reps_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='beaten_by',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beaten_pr', to='tracker.pr'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pr',
            name='invalidation_reason',
            field=models.CharField(blank=True, choices=[('EXPIRED', 'Expired'), ('BEATEN', 'Beaten')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pr',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INVALIDATED', 'Invalidated')], default='ACTIVE'),
        ),
    ]
