# Generated by Django 5.2.11 on 2026-05-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_alter_pr_beaten_by_alter_pr_invalidated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pattern',
            field=models.CharField(choices=[('VERTICAL_PUSH', 'Vertical Push'), ('HORIZONTAL_PUSH', 'Horizontal Push'), ('VERTICAL_PULL', 'Vertical Pull'), ('HORIZONTAL_PULL', 'Horizontal Pull'), ('SQUAT', 'Squat'), ('HINGE', 'Hinge'), ('CARRY', 'Carry'), ('CORE', 'Core'), ('OTHER', 'Other')], max_length=15),
        ),
    ]
