# Generated by Django 5.2.11 on 2026-05-28 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_alter_exercise_name_alter_exercise_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_bodyweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pr',
            name='pr_metric',
            field=models.CharField(choices=[('E1RM', 'Estimated 1RM'), ('REPS', 'Reps')], default='E1RM', max_length=4),
        ),
        migrations.AddField(
            model_name='set',
            name='is_bodyweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pr',
            name='e1rm_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pr',
            name='reps',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
